#!/usr/bin/env bash

# Default Ubuntu coverage for the autogenerated Feature test.
command -v zsh
getent passwd vscode
test "$(id -u vscode)" = "1000"
test "$(id -g vscode)" = "1000"
test "$(getent passwd vscode | cut -d: -f7)" = "/bin/zsh"
test -d /home/vscode/.oh-my-zsh
grep -q 'ZSH_THEME="agnoster"' /home/vscode/.zshrc
test -f /etc/sudoers.d/vscode
visudo -cf /etc/sudoers.d/vscode
test "$(su -s /bin/bash - vscode -c 'printf "%s" "$LANG"')" = "en_US.UTF-8"
test "$(su -s /bin/bash - vscode -c 'printf "%s" "$LC_ALL"')" = "en_US.UTF-8"
